/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'intro',
        'tutorials/distributed-locking',
        'tutorials/distributed-sequencer'
      ],
    },
    'getting-started',
    'why-kahuna',
    {
      type: 'category',
      label: 'Distributed Locks',
      items: [
        'distributed-locks',
        'distributed-locks/leases',
        'distributed-locks/fencing-tokens'
      ],
    },
    {
      type: 'category',
      label: 'Distributed Key/Value Store',
      items: [
        'distributed-keyvalue-store',
        'distributed-keyvalue-store/key-range-sharding',
        'distributed-keyvalue-store/load-based-range-splitting',
        'distributed-keyvalue-store/cas',
        'distributed-keyvalue-store/revisions',
        'distributed-keyvalue-store/transactions',
        'distributed-keyvalue-store/transaction-priority-admission',
        'distributed-keyvalue-store/buckets',
        'distributed-keyvalue-store/snapshot-holds'
      ],
    },
    {
      type: 'category',
      label: 'Distributed Sequencer',
      items: [
        'distributed-sequencer',
        'distributed-sequencer/model',
        'distributed-sequencer/idempotency',
        'distributed-sequencer/clients',
        'distributed-sequencer/api'
      ],
    },
    {
      type: 'category',
      label: 'Scripts',
      items: [
        'scripts',
        'scripts/basic-syntax',
        'scripts/types',
        'scripts/expressions',
        'scripts/control-structures',
        'scripts/commands/set',
        'scripts/commands/eset',
        'scripts/commands/get',
        'scripts/commands/eget',
        'scripts/commands/get-by-bucket',
        'scripts/commands/eget-by-bucket',
        'scripts/commands/scan-by-prefix',
        'scripts/commands/escan-by-prefix',
        'scripts/commands/extend',
        'scripts/commands/eextend',
        'scripts/commands/delete',
        'scripts/commands/edelete',
        'scripts/commands/exists',
        'scripts/commands/eexists',
        'scripts/functions/math',
        'scripts/functions/string',
        'scripts/functions/type',
      ],
    },
    {
      type: 'category',
      label: 'Server',
      items: [
        'server-installation',
        'server-configuration',
        'backend-io-scheduler',
        'leader-balancing',
        'backups-and-point-in-time-recovery',
        'embedded-kahuna-node',
        'benchmarking'
      ],
    },
    {
      type: 'category',
      label: 'Client',
      items: ['kahuna-cli', 'dotnet-client'],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/distributed-transactions',
        'architecture/raft',
        'architecture/hybrid-logical-clocks',
        'architecture/durability-levels',
        'architecture/partition-write-coalescing',
        'architecture/keys-eviction'
      ],
    },
    {
      type: 'category',
      label: 'Internals',
      items: [
        'internals',
        'internals/request-flow',
        'internals/transaction-lifecycle',
        'internals/actor-model',
        'internals/wal-and-persistence',
        'internals/backups-and-pitr',
        'internals/replication',
        'internals/mvcc',
        'internals/sequences'
      ],
    },
    {
      type: 'category',
      label: 'Storage',
      items: ['storage/overview'],
    },
    {
      type: 'category',
      label: 'Recipes',
      items: [
        'recipes/rate-limiting',
        'recipes/service-discoverability',
        'recipes/leader-election',
        'recipes/idempotent-jobs',
        'recipes/feature-flags',
        'recipes/ordered-ids',
        'recipes/inventory-reservation'
      ],
    },
  ],
};

export default sidebars;
